services:
  - type: web
    name: knl-api
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: CACHE_STORE
        value: file
      - key: APP_URL
        value: https://knl-api.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: knl-api-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://knl-atelier.netlify.app
      - key: CLOUDINARY_CLOUD_NAME
        value: tn2g2vcs
      - key: CLOUDINARY_API_KEY
        value: "765552648917614"
      - key: CLOUDINARY_API_SECRET
        value: UJpncHTKLBOjGyCeWKQfXEYTw7E
      - key: APP_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: knl-api-db
    plan: free
    ipAllowList: []
